-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 23:14:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema padaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema padaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `padaria` DEFAULT CHARACTER SET utf8 ;
USE `padaria` ;

-- -----------------------------------------------------
-- Table `padaria`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padaria`.`produto` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(18,2) UNSIGNED ZEROFILL NOT NULL,
  `unidade` VARCHAR(3) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
